// Code generated by Gopapageno; DO NOT EDIT.
package main

import (
	"github.com/giornetta/gopapageno"
	"strings"
	"fmt"
)

import (
	"math"
)

var parserInt64Pools []*gopapageno.Pool[int64]

// ParserPreallocMem initializes all the memory pools required by the semantic function of the parser.
func ParserPreallocMem(inputSize int, numThreads int) {
	parserInt64Pools = make([]*gopapageno.Pool[int64], numThreads)

	avgCharsPerNumber := float64(4)
	poolSizePerThread := int(math.Ceil((float64(inputSize) / avgCharsPerNumber) / float64(numThreads)))

	for i := 0; i < numThreads; i++ {
		parserInt64Pools[i] = gopapageno.NewPool[int64](poolSizePerThread)
	}
}


// Non-terminals
const (
	E = gopapageno.TokenEmpty + 1 + iota
	E_F_T
	E_T
	S
)

// Terminals
const (
	LPAR = gopapageno.TokenTerm + 1 + iota
	NUMBER
	PLUS
	RPAR
	TIMES
)

func SprintToken[ValueType any](root *gopapageno.Token) string {
	var sprintRec func(t *gopapageno.Token, sb *strings.Builder, indent string)

	sprintRec = func(t *gopapageno.Token, sb *strings.Builder, indent string) {
		if t == nil {
			return
		}

		sb.WriteString(indent)
		if t.Next == nil {
			sb.WriteString("└── ")
			indent += "    "
		} else {
			sb.WriteString("├── ")
			indent += "|   "
		}

		switch t.Type {
		case E:
			sb.WriteString("E")
		case E_F_T:
			sb.WriteString("E_F_T")
		case E_T:
			sb.WriteString("E_T")
		case S:
			sb.WriteString("S")
		case gopapageno.TokenEmpty:
			sb.WriteString("Empty")
		case LPAR:
			sb.WriteString("LPAR")
		case NUMBER:
			sb.WriteString("NUMBER")
		case PLUS:
			sb.WriteString("PLUS")
		case RPAR:
			sb.WriteString("RPAR")
		case TIMES:
			sb.WriteString("TIMES")
		case gopapageno.TokenTerm:
			sb.WriteString("Term")
		default:
			sb.WriteString("Unknown")
		}

		if t.Value != nil {
			if v, ok := any(t.Value).(*ValueType); ok {
				sb.WriteString(fmt.Sprintf(": %v", *v))
			}
		}
		
		sb.WriteString("\n")
		
		sprintRec(t.Child, sb, indent)
		sprintRec(t.Next, sb, indent[:len(indent)-4])
	}

	var sb strings.Builder
	
	sprintRec(root, &sb, "")
	
	return sb.String()
}

func NewGrammar() *gopapageno.Grammar {
	numTerminals := uint16(6)
	numNonTerminals := uint16(5)

	maxRHSLen := 3
	rules := []gopapageno.Rule{
		{S, []gopapageno.TokenType{E}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E, PLUS, E}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E, PLUS, E_F_T}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E, PLUS, E_T}, gopapageno.RuleSimple},
		{S, []gopapageno.TokenType{E_F_T}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E_F_T, PLUS, E}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E_F_T, PLUS, E_F_T}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E_F_T, PLUS, E_T}, gopapageno.RuleSimple},
		{E_T, []gopapageno.TokenType{E_F_T, TIMES, E_F_T}, gopapageno.RuleSimple},
		{E_T, []gopapageno.TokenType{E_F_T, TIMES, E_T}, gopapageno.RuleSimple},
		{S, []gopapageno.TokenType{E_T}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E_T, PLUS, E}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E_T, PLUS, E_F_T}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E_T, PLUS, E_T}, gopapageno.RuleSimple},
		{E_T, []gopapageno.TokenType{E_T, TIMES, E_F_T}, gopapageno.RuleSimple},
		{E_T, []gopapageno.TokenType{E_T, TIMES, E_T}, gopapageno.RuleSimple},
		{E_F_T, []gopapageno.TokenType{LPAR, E, RPAR}, gopapageno.RuleSimple},
		{E_F_T, []gopapageno.TokenType{LPAR, E_F_T, RPAR}, gopapageno.RuleSimple},
		{E_F_T, []gopapageno.TokenType{LPAR, E_T, RPAR}, gopapageno.RuleSimple},
		{E_F_T, []gopapageno.TokenType{NUMBER}, gopapageno.RuleSimple},
	}
	compressedRules := []uint16{0, 0, 5, 1, 13, 2, 36, 3, 74, 32769, 112, 32770, 145, 4, 0, 1, 32771, 18, 0, 0, 3, 1, 27, 2, 30, 3, 33, 1, 1, 0, 1, 2, 0, 1, 3, 0, 4, 4, 2, 32771, 43, 32773, 61, 0, 0, 3, 1, 52, 2, 55, 3, 58, 1, 5, 0, 1, 6, 0, 1, 7, 0, 0, 0, 2, 2, 68, 3, 71, 3, 8, 0, 3, 9, 0, 4, 10, 2, 32771, 81, 32773, 99, 0, 0, 3, 1, 90, 2, 93, 3, 96, 1, 11, 0, 1, 12, 0, 1, 13, 0, 0, 0, 2, 2, 106, 3, 109, 3, 14, 0, 3, 15, 0, 0, 0, 3, 1, 121, 2, 129, 3, 137, 0, 0, 1, 32772, 126, 2, 16, 0, 0, 0, 1, 32772, 134, 2, 17, 0, 0, 0, 1, 32772, 142, 2, 18, 0, 2, 19, 0	}

	precMatrix := [][]gopapageno.Precedence{
		{gopapageno.PrecEquals, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecEquals, gopapageno.PrecYields},
		{gopapageno.PrecTakes, gopapageno.PrecEquals, gopapageno.PrecEquals, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecTakes},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecAssociative, gopapageno.PrecTakes, gopapageno.PrecYields},
		{gopapageno.PrecTakes, gopapageno.PrecEquals, gopapageno.PrecEquals, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecTakes},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecAssociative},
	}
	bitPackedMatrix := []uint64{
		7674817019212293460, 233, 
	}

	fn := func(ruleDescription uint16, ruleFlags gopapageno.RuleFlags, lhs *gopapageno.Token, rhs []*gopapageno.Token, thread int){
		switch ruleDescription {
		case 0:
			S0 := lhs
			E1 := rhs[0]

			S0.Child = E1
			S0.LastChild = E1

			{
				S0.Value = E1.Value
			}
			_ = E1
		case 1:
			E0 := lhs
			E1 := rhs[0]
			PLUS2 := rhs[1]
			E3 := rhs[2]

			E0.Child = E1
			E1.Next = PLUS2
			PLUS2.Next = E3
			E0.LastChild = E3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E1.Value.(*int64) + *E3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E1
			_ = PLUS2
			_ = E3
		case 2:
			E0 := lhs
			E1 := rhs[0]
			PLUS2 := rhs[1]
			E_F_T3 := rhs[2]

			E0.Child = E1
			E1.Next = PLUS2
			PLUS2.Next = E_F_T3
			E0.LastChild = E_F_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E1.Value.(*int64) + *E_F_T3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E1
			_ = PLUS2
			_ = E_F_T3
		case 3:
			E0 := lhs
			E1 := rhs[0]
			PLUS2 := rhs[1]
			E_T3 := rhs[2]

			E0.Child = E1
			E1.Next = PLUS2
			PLUS2.Next = E_T3
			E0.LastChild = E_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E1.Value.(*int64) + *E_T3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E1
			_ = PLUS2
			_ = E_T3
		case 4:
			S0 := lhs
			E_F_T1 := rhs[0]

			S0.Child = E_F_T1
			S0.LastChild = E_F_T1

			{
				S0.Value = E_F_T1.Value
			}
			_ = E_F_T1
		case 5:
			E0 := lhs
			E_F_T1 := rhs[0]
			PLUS2 := rhs[1]
			E3 := rhs[2]

			E0.Child = E_F_T1
			E_F_T1.Next = PLUS2
			PLUS2.Next = E3
			E0.LastChild = E3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E_F_T1.Value.(*int64) + *E3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E_F_T1
			_ = PLUS2
			_ = E3
		case 6:
			E0 := lhs
			E_F_T1 := rhs[0]
			PLUS2 := rhs[1]
			E_F_T3 := rhs[2]

			E0.Child = E_F_T1
			E_F_T1.Next = PLUS2
			PLUS2.Next = E_F_T3
			E0.LastChild = E_F_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E_F_T1.Value.(*int64) + *E_F_T3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E_F_T1
			_ = PLUS2
			_ = E_F_T3
		case 7:
			E0 := lhs
			E_F_T1 := rhs[0]
			PLUS2 := rhs[1]
			E_T3 := rhs[2]

			E0.Child = E_F_T1
			E_F_T1.Next = PLUS2
			PLUS2.Next = E_T3
			E0.LastChild = E_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E_F_T1.Value.(*int64) + *E_T3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E_F_T1
			_ = PLUS2
			_ = E_T3
		case 8:
			E_T0 := lhs
			E_F_T1 := rhs[0]
			TIMES2 := rhs[1]
			E_F_T3 := rhs[2]

			E_T0.Child = E_F_T1
			E_F_T1.Next = TIMES2
			TIMES2.Next = E_F_T3
			E_T0.LastChild = E_F_T3

			{
			    newValue := parserInt64Pools[thread].Get()
			    *newValue = *E_F_T1.Value.(*int64) * *E_F_T3.Value.(*int64)
			    E_T0.Value = newValue
			}
			_ = E_F_T1
			_ = TIMES2
			_ = E_F_T3
		case 9:
			E_T0 := lhs
			E_F_T1 := rhs[0]
			TIMES2 := rhs[1]
			E_T3 := rhs[2]

			E_T0.Child = E_F_T1
			E_F_T1.Next = TIMES2
			TIMES2.Next = E_T3
			E_T0.LastChild = E_T3

			{
			    newValue := parserInt64Pools[thread].Get()
			    *newValue = *E_F_T1.Value.(*int64) * *E_T3.Value.(*int64)
			    E_T0.Value = newValue
			}
			_ = E_F_T1
			_ = TIMES2
			_ = E_T3
		case 10:
			S0 := lhs
			E_T1 := rhs[0]

			S0.Child = E_T1
			S0.LastChild = E_T1

			{
				S0.Value = E_T1.Value
			}
			_ = E_T1
		case 11:
			E0 := lhs
			E_T1 := rhs[0]
			PLUS2 := rhs[1]
			E3 := rhs[2]

			E0.Child = E_T1
			E_T1.Next = PLUS2
			PLUS2.Next = E3
			E0.LastChild = E3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E_T1.Value.(*int64) + *E3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E_T1
			_ = PLUS2
			_ = E3
		case 12:
			E0 := lhs
			E_T1 := rhs[0]
			PLUS2 := rhs[1]
			E_F_T3 := rhs[2]

			E0.Child = E_T1
			E_T1.Next = PLUS2
			PLUS2.Next = E_F_T3
			E0.LastChild = E_F_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E_T1.Value.(*int64) + *E_F_T3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E_T1
			_ = PLUS2
			_ = E_F_T3
		case 13:
			E0 := lhs
			E_T1 := rhs[0]
			PLUS2 := rhs[1]
			E_T3 := rhs[2]

			E0.Child = E_T1
			E_T1.Next = PLUS2
			PLUS2.Next = E_T3
			E0.LastChild = E_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E_T1.Value.(*int64) + *E_T3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E_T1
			_ = PLUS2
			_ = E_T3
		case 14:
			E_T0 := lhs
			E_T1 := rhs[0]
			TIMES2 := rhs[1]
			E_F_T3 := rhs[2]

			E_T0.Child = E_T1
			E_T1.Next = TIMES2
			TIMES2.Next = E_F_T3
			E_T0.LastChild = E_F_T3

			{
			    newValue := parserInt64Pools[thread].Get()
			    *newValue = *E_T1.Value.(*int64) * *E_F_T3.Value.(*int64)
			    E_T0.Value = newValue
			}
			_ = E_T1
			_ = TIMES2
			_ = E_F_T3
		case 15:
			E_T0 := lhs
			E_T1 := rhs[0]
			TIMES2 := rhs[1]
			E_T3 := rhs[2]

			E_T0.Child = E_T1
			E_T1.Next = TIMES2
			TIMES2.Next = E_T3
			E_T0.LastChild = E_T3

			{
			    newValue := parserInt64Pools[thread].Get()
			    *newValue = *E_T1.Value.(*int64) * *E_T3.Value.(*int64)
			    E_T0.Value = newValue
			}
			_ = E_T1
			_ = TIMES2
			_ = E_T3
		case 16:
			E_F_T0 := lhs
			LPAR1 := rhs[0]
			E2 := rhs[1]
			RPAR3 := rhs[2]

			E_F_T0.Child = LPAR1
			LPAR1.Next = E2
			E2.Next = RPAR3
			E_F_T0.LastChild = RPAR3

			{
				E_F_T0.Value = E2.Value
			}
			_ = LPAR1
			_ = E2
			_ = RPAR3
		case 17:
			E_F_T0 := lhs
			LPAR1 := rhs[0]
			E_F_T2 := rhs[1]
			RPAR3 := rhs[2]

			E_F_T0.Child = LPAR1
			LPAR1.Next = E_F_T2
			E_F_T2.Next = RPAR3
			E_F_T0.LastChild = RPAR3

			{
				E_F_T0.Value = E_F_T2.Value
			}
			_ = LPAR1
			_ = E_F_T2
			_ = RPAR3
		case 18:
			E_F_T0 := lhs
			LPAR1 := rhs[0]
			E_T2 := rhs[1]
			RPAR3 := rhs[2]

			E_F_T0.Child = LPAR1
			LPAR1.Next = E_T2
			E_T2.Next = RPAR3
			E_F_T0.LastChild = RPAR3

			{
				E_F_T0.Value = E_T2.Value
			}
			_ = LPAR1
			_ = E_T2
			_ = RPAR3
		case 19:
			E_F_T0 := lhs
			NUMBER1 := rhs[0]

			E_F_T0.Child = NUMBER1
			E_F_T0.LastChild = NUMBER1

			{
				E_F_T0.Value = NUMBER1.Value
			}
			_ = NUMBER1
		}
		_ = ruleFlags
	}

	return &gopapageno.Grammar{
		NumTerminals:  numTerminals,
		NumNonterminals: numNonTerminals,
		MaxRHSLength: maxRHSLen,
		Rules: rules,
		CompressedRules: compressedRules,
		PrecedenceMatrix: precMatrix,
		BitPackedPrecedenceMatrix: bitPackedMatrix,
		Func: fn,
		ParsingStrategy: gopapageno.AOPP,
		PreambleFunc: ParserPreallocMem,
	}
}

