version: '3'

vars:
  EXAMPLE: adder
  STRAT: opp
  FNAME: 'default'

tasks:
  generate:
    cmds:
      - go run ./cmd/gopapageno/main.go -l ./examples/{{ .STRAT }}/{{ .EXAMPLE }}.l -g {{ .STRAT }}/{{ .EXAMPLE }}.g -o {{ .STRAT }}/ -strategy={{ .STRAT }} -log

  benchmark:
    vars:
      COUNT: 10
    cmds:
      - go test github.com/giornetta/gopapageno/examples/{{ .EXAMPLE }}/{{ .STRAT }} -bench . -count={{ .COUNT }} > ./examples/{{ .EXAMPLE }}/benchmark_results/{{ .STRAT }}-{{ .FNAME }}.txt

  benchmark-all:
    cmds:
      - task: benchmark
        vars: { STRAT: 'opp'}
      - task: benchmark
        vars: { STRAT: 'aopp' }
      - task: benchmark
        vars: { STRAT: 'copp' }

  compare-benchmarks-win:
    platforms: [windows]
    cmds:
      - (Get-Content -Path "./examples/{{ .EXAMPLE }}/benchmark_results/{{ .STRAT }}.txt") -replace "{{ .STRAT }}", "" | Set-Content -Path "./examples/{{ .EXAMPLE }}/benchmark_results/{{ .STRAT }}.txt"
